### ISSUE TITLE
A function to convert a device id (int_value) to a device slug

### ISSUE THREAD

**Issue by lekosfmi** [iotile/ng2-iotile-cloud#26]
A sample function we use on mobile: 

`export function deviceIDToSlug(deviceID: number) {
        let hexString = Number(deviceID).toString(16);        
        while (hexString.length < 16) {
            hexString = '0' + hexString;
        }
        hexString = hexString.toLowerCase();
        return 'd--' + hexString.substr(0, 4) + '-' + hexString.substr(4, 4) + '-' + hexString.substr(8, 4) + '-' + hexString.substr(12, 4);
}`

**Comment by dkarchmer** [comment]
Done

```
let dev424: DeviceGlobalId = new DeviceGlobalId(424);
expect(dev424.toString()).toEqual('d--0000-0000-0000-01a8');
```
